### ISSUE TITLE
Ember.onerror error while running tests

### ISSUE THREAD

**Issue by Windvis** [appaloosa-store/ember-cli-bugsnag-reporter#5]
When I run the tests locally I see the following error:

```
not ok 17 Chrome 78.0 - [2 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/test-support.js:10953:16)
                at runTest (http://localhost:7357/assets/test-support.js:4394:30)
                at Test.run (http://localhost:7357/assets/test-support.js:4380:6)
                at http://localhost:7357/assets/test-support.js:4601:12
                at advanceTaskQueue (http://localhost:7357/assets/test-support.js:3993:6)
                at advance (http://localhost:7357/assets/test-support.js:3974:4)
        message: >
            Ember.onerror handler with invalid testing behavior detected. An Ember.onerror handler _must_ rethrow exceptions when `Ember.testing` is `true` or the test suite is unreliable. See https://git.io/vbine for more details.
        negative: >
            false
        browser log: |
            ERROR: [object Object] [object Object]
    ...
```

The link in the error message leads to [this page](https://github.com/emberjs/ember-qunit/pull/304) and provides more information about how to fix it.

**Comment by Mifrill** [comment]
Hey, @KamiKillertO can you do some updates on this, please? I have an intermittent test freeze with the same issue.
Hey, @Windvis, did you resolve it?

**Comment by Mifrill** [comment]
Hey, @Windvis I've resolved it by restore Ember.onerror mock:
```
import Ember from 'ember';

const { Test, Logger } = Ember;

export default function mockAdapterErrors(hooks = self) {
  hooks.beforeEach(function() {
    interceptExceptions.call(this);
  });

  hooks.afterEach(function() {
    restoreExceptions.call(this);
  });
}

export function interceptExceptions() {
  this.originalLoggerError = Logger.error;
  this.originalTestAdapterException = Test.adapter.exception;
  this.originalOnError = Ember.onerror;
  Logger.error = () => {};
  Test.adapter.exception = () => {};
  Ember.onerror = () => {};
}

export function restoreExceptions() {
  Logger.error = this.originalLoggerError;
  Test.adapter.exception = this.originalTestAdapterException;
  Ember.onerror = this.originalOnError;
}
```
